### ISSUE TITLE
Upgrade to Ultradom

### ISSUE THREAD

**Issue by jorgebucaran** [pickle-ts/pickle#1]
Hi @pickle-ts. [Ultradom](https://github.com/jorgebucaran/ultradom) is the continuation of and successor to Picodom. 

Could you update your dependencies / code / etc? Also please update your repository's tags — remove `picodom` and change it to `ultradom`. 

Cheers! 👋

**Comment by solenya-group** [comment]
Hi Jorge - just done a big update to pickle including porting over the latest version of Ultradom to Typescript. Perhaps that might be useful to you. Many thanks to you for Ultradom!

Cheers
